// AUTO-GENERATED by scripts/generate-flags.mjs — do not edit manually.
const flags: Record<string, () => Promise<any>> = {
  'dk': () => import('./assets/flags/dk.svg'),
  'ee': () => import('./assets/flags/ee.svg'),
  'fr': () => import('./assets/flags/fr.svg'),
  'gb': () => import('./assets/flags/gb.svg'),
  'is': () => import('./assets/flags/is.svg'),
  'it': () => import('./assets/flags/it.svg'),
  'lt': () => import('./assets/flags/lt.svg'),
  'lv': () => import('./assets/flags/lv.svg'),
  'no': () => import('./assets/flags/no.svg'),
  'se': () => import('./assets/flags/se.svg'),
}

export default flags
