// AUTO-GENERATED by scripts/generate-flags.mjs — do not edit manually.
import type { App } from 'vue'
import DkFlag from './assets/flags/dk.svg'
import EeFlag from './assets/flags/ee.svg'
import FrFlag from './assets/flags/fr.svg'
import GbFlag from './assets/flags/gb.svg'
import IsFlag from './assets/flags/is.svg'
import ItFlag from './assets/flags/it.svg'
import LtFlag from './assets/flags/lt.svg'
import LvFlag from './assets/flags/lv.svg'
import NoFlag from './assets/flags/no.svg'
import SeFlag from './assets/flags/se.svg'
import CountryFlag from './CountryFlag.vue'

export { CountryFlag,
  DkFlag,
  EeFlag,
  FrFlag,
  GbFlag,
  IsFlag,
  ItFlag,
  LtFlag,
  LvFlag,
  NoFlag,
  SeFlag,
}

export const CountryFlagPlugin = {
  install(app: App) {
    app.component('CountryFlag', CountryFlag)
  }
}

export default CountryFlag
